version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      timezone: "America/Chicago"
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "jwryan9"
    labels:
      - "type: dependabot"
      - "status: todo"